# These are supported funding model platforms

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-open-collective
# ko_fi: your-ko-fi
# tidelift: npm/your-package-name
# community_bridge: your-project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# custom: https://your-website.com

# Uncomment and update with your funding information
